### ISSUE TITLE
Fix frontend validations for Add Expense Modal's amount field and server-side error population

### ISSUE THREAD

**Issue by ethanharrasser** [OrangeTabia/fairshare#42]
Currently, it is possible to submit a new expense with a non-numeric value, which raises a 400 error but no error messages appear. Form should probably populate backend errors, and the amount field's frontend validations should account for invalid input format

**Comment by llfbh33** [comment]
Set the input to only take in numeric (numbers and decimals)  I believe this removes the need for the validations.  However the user is unable to use commas.  If someone is against this we can try to come up with a different solution.
